all: saber.cpp dnablock.h dnablock.cpp utils.h utils.cpp bed.h bed.cpp ed.h ed.cpp constants.h types.h edlib/edlib/src/edlib.cpp edlib/edlib/include/edlib.h
	g++ -Wall -o saber saber.cpp dnablock.h dnablock.cpp utils.h utils.cpp bed.h bed.cpp ed.h ed.cpp constants.h types.h edlib/edlib/src/edlib.cpp edlib/edlib/include/edlib.h -I edlib/edlib/include
	
sim: rearrangement_sim.cpp dnablock.h dnablock.cpp utils.h utils.cpp bed.h bed.cpp ed.h ed.cpp constants.h types.h edlib/edlib/src/edlib.cpp edlib/edlib/include/edlib.h
	g++ -Wall -o rearrangement_sim rearrangement_sim.cpp dnablock.h dnablock.cpp utils.h utils.cpp bed.h bed.cpp ed.h ed.cpp constants.h types.h edlib/edlib/src/edlib.cpp edlib/edlib/include/edlib.h -I edlib/edlib/include
	
